ALTER TABLE "Member" ADD COLUMN IF NOT EXISTS "selfServiceTokenAliases" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Guest" ADD COLUMN IF NOT EXISTS "selfServiceTokenAliases" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
